import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import MovieContextProvider from "@/context/MovieContext";
import UserContextProvider from "@/context/UserContext";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserContextProvider>
      <MovieContextProvider>
        <html lang="en">
          <body className={inter.className}>
            <SideBar />
            <Header />
            {children}
            <SpeedInsights />
          </body>
        </html>
      </MovieContextProvider>
    </UserContextProvider>
  );
}
