import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";
import MovieContextProvider from "@/context/MovieContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <MovieContextProvider>
        <html lang="en">
          <body className={inter.className}>
            <SideBar />
            <Header />
            {children}
          </body>
        </html>
      </MovieContextProvider>
    </ClerkProvider>
  );
}
